### ISSUE TITLE
Regarding a freelance task, are you interested?

### ISSUE THREAD

**Issue by seekingdeep** [crismolav/ggnn#2]
@crismolav hi there,
i have a task that i want to solve using GNNs, 
are you interested in freelancing?
what is your email so i can share furthur information 

waiting for your reply

**Comment by crismolav** [comment]
Hey,
I would be interested. Can you give me more information about it?

Regards,

Cristian

**Comment by seekingdeep** [comment]
@crismolav 
what is your email so i can't share more information

**Comment by crismolav** [comment]
cmoraleso@utexas.edu
